---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  nginx.conf: |
    events {
      use epoll;
    }
    http {
        server {
            listen 8090;
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri “/index.html”;
            }
            location /api {
                proxy_pass http://backend:8080;
            }
        }
    }
