---
apiVersion: v1
kind: Service
metadata:
   name: frontend
   labels:
     app: frontend
spec:
  type: ClusterIP
  ports:
# внешний порт для сервиса
    - port: 8090
      protocol: TCP
# внешний порт самого пода
      targetPort: 8090
  selector:
    app: frontend
