---
apiVersion: v1
kind: Secret
metadata:
  name: vault-backend
  labels:
    app: backend
data:
  vault_token: aHZzLk1uSFphaDJlU3F1SFFaU2Y2OVRLTHZRTQ==
# необходимо условие для кодирования без переноса строки
# echo -n "hvs.MnHZah2eSquHQZSf69TKLvQM" | base64 - без переноса строки
# echo "hvs.MnHZah2eSquHQZSf69TKLvQM" | base64 - с переносом строки
# aHZzLk1uSFphaDJlU3F1SFFaU2Y2OVRLTHZRTQ== после кодирования без переноса строки
# aHZzLk1uSFphaDJlU3F1SFFaU2Y2OVRLTHZRTQo= после кодирования с переносом строки
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-login-secrets-backend
data:
  .dockerconfigjson: >-
     ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllXNWhkRzlzZVhCeWFXMWhPbG90YnpaNldGODJUVUpHTm5wV2NEWkxhRXg1IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
