---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rc1b-hbgrshwk67xn4wfm.mdb.yandexcloud.net:6432/anatolyprima
            - name: SPRING_DATASOURCE_USERNAME
              value: anatolyprima
            - name: REPORT_PATH
              value: ./logs

            - name: spring.data.mongodb.uri
              value: mongodb://anatolyprima:Testusr1234@rc1b-dkdiam8q2r06t1bi.mdb.yandexcloud.net:27018/anatolyprima?tls=true&replicaSet=rs01
            - name: spring.datasource.password
              value: anatolyprima
            - name: spring.datasource.username
              value: anatolyprima


            - name: VAULT_HOST
              value: 178.154.206.140
            - name: VAULT_TOLEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token

          ports:
            - name: backend
              containerPort: 8080

      imagePullSecrets:
        - name: vault
        - name: docker-login-secrets
