---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLk1uSFphaDJlU3F1SFFaU2Y2OVRLTHZRTQo=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-login-secret
data:
  .dockerconfigjson: >-
     ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllXNWhkRzlzZVhCeWFXMWhPbG90YnpaNldGODJUVUpHTm5wV2NEWkxhRXg1IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
