version: "3.3"
services:

  backend:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-backend:latest
#    image: $CI_REGISTRY/anatolyprima/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend
    env_file:
      - .env_docker_backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}#
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
#      BACKEND_VERSION:
    networks:
      - sausage-store

  backend-report:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-backend-report:latest
#    image: $CI_REGISTRY/anatolyprima/sausage-store/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    env_file:
      - .env_docker_backend_report
#    environment:
#      BACKEND_REPORT_VERSION: latest
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-frontend:latest
#    image: $CI_REGISTRY/anatolyprima/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    env_file:
      - .env_docker_frontend
#    environment:
#      FRONTEND_VERSION: latest
    ports:
      - "8080:80"
    networks:
      - sausage-store

#  vault:
#    image: vault
#    container_name: vault
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
#      VAULT_SERVER: "http://127.0.0.1:8200"
#      VAULT_ADDR: "http://127.0.0.1:8200"
#    env_file:
#      - .env_docker_backend
#    networks:
#      - sausage-store

networks:
  sausage-store:
