version: "3.3"
services:

  backend:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    env_file:
      - .env_docker_backend
    restart: always
    networks:
      - sausage-store

  backend-report:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    env_file:
      - .env_docker_backend_report
    restart: always
    networks:
      - sausage-store
    expose:
      - "8081"

  frontend:
    image: gitlab.praktikum-services.ru:5050/anatolyprima/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    env_file:
      - .env_docker_frontend
    ports:
      - "8080:80"
    networks:
      - sausage-store

networks:
  sausage-store:
